#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Auto-generated by pickfunc
Source root: /home/yuepeng/code/multi_objective_opf/main_part
Extracted functions: train_unsupervised_ngt_flow, train_unsupervised_ngt
"""

# ===== Extracted function definitions =====

# --- from: /home/yuepeng/code/multi_objective_opf/main_part/train.py (L1057-L1941) ---
def train_unsupervised_ngt_flow(config, sys_data=None, device=None, 
                                 lambda_cost=0.9, lambda_carbon=0.1,
                                 flow_inf_steps=10, use_projection=False,
                                 anchor_model_path=None, anchor_preference=None,
                                 tb_logger=None, zero_init=True, debug=False):
    """
    DeepOPF-NGT Unsupervised Training with Rectified Flow Model.
    
    This function replaces the direct MLP (NetV) prediction with a Rectified Flow model.
    The flow model uses VAE predictions or a pretrained Flow model as anchors.
    
    Key features:
    1. Uses PreferenceConditionedNetV (flow model) instead of NetV (MLP)
    2. Supports two anchor modes:
       - VAE anchor (default): Use pretrained VAE for initial anchor
       - Flow anchor (progressive): Use a previously trained Flow model
    3. Supports preference conditioning for multi-objective optimization
    4. Optionally supports projection method for constraint satisfaction
    
    Progressive Training (anchor_model_path provided):
        z_anchor = PrevFlow(x, pref_prev)  # Get anchor from previous Flow model
        V_pred = ∫v(x,z,t,pref_new)dt      # Train new Flow for new preference
        
    This allows curriculum learning:
        VAE → Flow(1.0→0.9) → Flow(0.9→0.8) → ... → Flow(0.2→0.1)
    
    Args:
        config: Configuration object with ngt_* parameters
        sys_data: PowerSystemData object (optional, will load if None)
        device: Device (optional, uses config.device if None)
        lambda_cost: Economic cost preference weight (default: 0.9)
        lambda_carbon: Carbon emission preference weight (default: 0.1)
        flow_inf_steps: Number of flow integration steps (default: 10)
        use_projection: Whether to use tangent-space projection (default: False)
        anchor_model_path: Path to pretrained Flow model for anchor (None = use VAE)
        anchor_preference: Preference used by anchor Flow model [λ_cost, λ_carbon] (required if anchor_model_path is set)
        tb_logger: TensorBoardLogger instance for logging (optional)
        zero_init: Whether to initialize flow model output near zero (default: True)
        debug: If True, skip training and load pre-trained model from fixed path (default: False)
        
    Returns:
        model: Trained flow model (PreferenceConditionedNetV)
        loss_history: Dictionary of training losses
        time_train: Training time in seconds
        ngt_data: NGT training data dictionary
        sys_data: Updated system data
    """ 
    
    print('=' * 70)
    print('DeepOPF-NGT Unsupervised Training with Rectified Flow Model')
    print('=' * 70)
    print(f'Preference: lambda_cost={lambda_cost}, lambda_carbon={lambda_carbon}')
    print(f'Flow steps: {flow_inf_steps}, Projection: {use_projection}')
    
    # Device setup
    if device is None:
        device = config.device
    
    # ============================================================
    # Step 1: Load NGT-specific training data
    # ============================================================
    ngt_data, sys_data = load_ngt_training_data(config, sys_data)
    
    input_dim = ngt_data['input_dim']
    output_dim = ngt_data['output_dim']
    Vscale = ngt_data['Vscale'].to(device)
    Vbias = ngt_data['Vbias'].to(device)
    
    print(f"\nModel configuration:")
    print(f"  Input dim: {input_dim}")
    print(f"  Output dim: {output_dim} (Va: {ngt_data['NPred_Va']}, Vm: {ngt_data['NPred_Vm']})")
    print(f"  Epochs: {config.ngt_Epoch}")
    print(f"  Batch size: {config.ngt_batch_size}")
    print(f"  Learning rate: {config.ngt_Lr}")
    
    # ============================================================
    # Step 2: Determine anchor mode and load anchor models
    # ============================================================
    # Two anchor modes:
    # 1. VAE anchor (default): anchor_model_path is None
    # 2. Flow anchor (progressive): anchor_model_path points to previous Flow model
    
    use_flow_anchor = anchor_model_path is not None
    bus_slack = int(sys_data.bus_slack)
    
    from models import create_model, PreferenceConditionedNetV
    
    if use_flow_anchor:
        # ==================== Flow Anchor Mode (Progressive Training) ====================
        print("\n--- Loading Flow Anchor Model (Progressive Training) ---")
        
        if anchor_preference is None:
            raise ValueError("anchor_preference must be provided when using anchor_model_path")
        
        if not os.path.exists(anchor_model_path):
            raise FileNotFoundError(f"Anchor Flow model not found: {anchor_model_path}")
        
        print(f"  Anchor model: {anchor_model_path}")
        print(f"  Anchor preference: λ_cost={anchor_preference[0]}, λ_carbon={anchor_preference[1]}")
        print(f"  Target preference: λ_cost={lambda_cost}, λ_carbon={lambda_carbon}")
        
        # Create anchor Flow model with same architecture
        hidden_dim = getattr(config, 'ngt_flow_hidden_dim', 144)
        num_layers = getattr(config, 'ngt_flow_num_layers', 2)
        
        anchor_flow_model = PreferenceConditionedNetV(
            input_dim=input_dim,
            output_dim=output_dim,
            hidden_dim=hidden_dim,
            num_layers=num_layers,
            Vscale=Vscale,
            Vbias=Vbias,
            preference_dim=2,
            preference_hidden=64
        )
        anchor_flow_model.to(device)
        
        # Load anchor model weights
        anchor_flow_model.load_state_dict(
            torch.load(anchor_model_path, map_location=device, weights_only=True)
        )
        anchor_flow_model.eval()
        
        # Freeze anchor model
        for param in anchor_flow_model.parameters():
            param.requires_grad = False
        
        print(f"  Anchor Flow model loaded and frozen.")
        
        # Store anchor preference for later use
        anchor_pref_tensor = torch.tensor([anchor_preference], dtype=torch.float32, device=device)
        
        # We still need VAE for the initial anchor to the anchor Flow model
        # (unless we want to chain from another Flow model, but let's keep it simple)
        # Load VAE as the base anchor
        vae_vm_path = config.pretrain_model_path_vm
        vae_va_path = config.pretrain_model_path_va
        
        if os.path.exists(vae_vm_path) and os.path.exists(vae_va_path):
            vae_input_dim = input_dim
            vae_vm = create_model('vae', vae_input_dim, config.Nbus, config, is_vm=True)
            vae_va = create_model('vae', vae_input_dim, config.Nbus - 1, config, is_vm=False)
            vae_vm.to(device)
            vae_va.to(device)
            vae_vm.load_state_dict(torch.load(vae_vm_path, map_location=device, weights_only=True), strict=True)
            vae_va.load_state_dict(torch.load(vae_va_path, map_location=device, weights_only=True), strict=True)
            vae_vm.eval()
            vae_va.eval()
            for param in vae_vm.parameters():
                param.requires_grad = False
            for param in vae_va.parameters():
                param.requires_grad = False
            print(f"  VAE models also loaded (for base anchor to Flow).")
        else:
            vae_vm, vae_va = None, None
            print(f"  [Warning] VAE models not found, will use zeros as base anchor.")
    else:
        # ==================== VAE Anchor Mode (Default) ====================
        print("\n--- Loading VAE Anchor Models ---")
        anchor_flow_model = None
        anchor_pref_tensor = None
        
        # Check if VAE models exist
        vae_vm_path = config.pretrain_model_path_vm
        vae_va_path = config.pretrain_model_path_va
        
        if not os.path.exists(vae_vm_path):
            raise FileNotFoundError(f"Pretrained VAE (Vm) not found: {vae_vm_path}\n"
                                   f"Please train VAE models first using supervised training.")
        if not os.path.exists(vae_va_path):
            raise FileNotFoundError(f"Pretrained VAE (Va) not found: {vae_va_path}\n"
                                   f"Please train VAE models first using supervised training.")
        
        # Load VAE models
        vae_input_dim = input_dim
        
        vae_vm = create_model('vae', vae_input_dim, config.Nbus, config, is_vm=True)
        vae_va = create_model('vae', vae_input_dim, config.Nbus - 1, config, is_vm=False)
        
        vae_vm.to(device)
        vae_va.to(device)
        
        # Load state dicts (use strict=True to catch dimension mismatches early)
        print(f"  Loading Vm VAE from: {vae_vm_path}")
        vae_vm.load_state_dict(torch.load(vae_vm_path, map_location=device, weights_only=True), strict=True)
        print(f"  Loading Va VAE from: {vae_va_path}")
        vae_va.load_state_dict(torch.load(vae_va_path, map_location=device, weights_only=True), strict=True)
        
        vae_vm.eval()
        vae_va.eval()
        
        # Freeze VAE parameters
        for param in vae_vm.parameters():
            param.requires_grad = False
        for param in vae_va.parameters():
            param.requires_grad = False
        
        print(f"  VAE models loaded and frozen.")
    
    # ============================================================
    # Step 3: Create Flow model (PreferenceConditionedNetV)
    # ============================================================
    # Note: PreferenceConditionedNetV already imported above
    
    hidden_dim = getattr(config, 'ngt_flow_hidden_dim', 144)
    num_layers = getattr(config, 'ngt_flow_num_layers', 2)
    
    model = PreferenceConditionedNetV(
        input_dim=input_dim,
        output_dim=output_dim,
        hidden_dim=hidden_dim,
        num_layers=num_layers,
        Vscale=Vscale,
        Vbias=Vbias,
        preference_dim=2,
        preference_hidden=64
    )
    model.to(device)
    
    print(f"\nFlow model (PreferenceConditionedNetV) created:")
    print(f"  Hidden dim: {hidden_dim}, Num layers: {num_layers}")
    print(f"  Total parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # Initialize flow model output near zero (so initial velocity is small)
    if zero_init:
        initialize_flow_model_near_zero(model, scale=0.01)
        print("  Flow model output layer initialized near zero (scale=0.01)")
    
    # ============================================================
    # Debug Mode: Load pre-trained model and skip training
    # ============================================================
    if debug:
        debug_model_path = '/home/yuepeng/code/multi_objective_opf/main_part/saved_models/NetV_ngt_flow_300bus_lc05_E1000_final.pth'
        print(f"\n{'=' * 70}")
        print(f"[Debug Mode] Loading pre-trained model (skipping training)")
        print(f"{'=' * 70}")
        print(f"Model path: {debug_model_path}")
        
        if not os.path.exists(debug_model_path):
            raise FileNotFoundError(f"Debug model not found: {debug_model_path}")
        
        # Load model weights
        model.load_state_dict(torch.load(debug_model_path, map_location=device, weights_only=True))
        model.eval()
        print(f"  Model loaded successfully.")
        
        # Create empty loss history for compatibility
        loss_history = {
            'total': [],
            'kgenp_mean': [],
            'kgenq_mean': [],
            'kpd_mean': [],
            'kqd_mean': [],
            'kv_mean': [],
            'cost': [],
            'carbon': [],
        }
        
        # Set time_train to 0 (no training time)
        time_train = 0.0
        
        # Initialize P_tan_t to None (will be set if use_projection is True)
        P_tan_t = None
        if use_projection:
            # Setup projection matrix for debug mode
            try:
                from flow_model.post_processing import ConstraintProjectionV2
                print("\n--- Setting up Constraint Projection (Debug Mode) ---")
                projector = ConstraintProjectionV2(sys_data, config, use_historical_jacobian=True)
                P_tan_full, _, _ = projector.compute_projection_matrix()
                
                bus_Pnet_all = ngt_data['bus_Pnet_all']
                bus_slack = int(sys_data.bus_slack)
                Nbus = config.Nbus
                
                bus_Pnet_noslack = bus_Pnet_all[bus_Pnet_all != bus_slack]
                all_buses_noslack = np.concatenate([np.arange(bus_slack), np.arange(bus_slack+1, Nbus)])
                
                idx_Vm_in_Ptan = bus_Pnet_all
                idx_Va_in_Ptan = []
                for bus in bus_Pnet_noslack:
                    pos = np.where(all_buses_noslack == bus)[0][0]
                    idx_Va_in_Ptan.append(Nbus + pos)
                idx_Va_in_Ptan = np.array(idx_Va_in_Ptan)
                
                # Combine indices: [Vm indices, Va indices]
                idx_flow_in_Ptan = np.concatenate([idx_Va_in_Ptan, idx_Vm_in_Ptan])
                # Extract submatrix for Flow output dimensions (both rows and columns)
                P_tan_flow = P_tan_full[np.ix_(idx_flow_in_Ptan, idx_flow_in_Ptan)]
                P_tan_t = torch.from_numpy(P_tan_flow).float().to(device)
                print(f"  Full projection matrix shape: {P_tan_full.shape}")
                print(f"  Flow projection matrix shape: {P_tan_t.shape}")
                print(f"  Flow output dim: {len(idx_flow_in_Ptan)}")
            except Exception as e:
                print(f"  Warning: Could not setup projection matrix in debug mode: {e}")
                P_tan_t = None
        
        print(f"\n[Debug Mode] Model loaded, returning without training.")
        return model, loss_history, time_train, ngt_data, sys_data, use_projection, P_tan_t
    
    # ============================================================
    # Step 4: Create optimizer (matching MLP training - no weight_decay, no scheduler)
    # ============================================================
    optimizer = torch.optim.Adam(model.parameters(), lr=config.ngt_Lr)
    
    # ============================================================
    # Step 5: Create loss function
    # ============================================================
    # CRITICAL FIX: Sync lambda values from function parameters to config
    # This ensures loss_fn uses the same lambda values as preference conditioning
    # DeepOPFNGTLoss reads lambda from config.ngt_lambda_cost/ngt_lambda_carbon
    config.ngt_lambda_cost = lambda_cost
    config.ngt_lambda_carbon = lambda_carbon
    # Also ensure multi-objective is enabled if lambda values are provided
    if not hasattr(config, 'ngt_use_multi_objective') or not config.ngt_use_multi_objective:
        config.ngt_use_multi_objective = True
    print(f"[Flow Training] Synced lambda values to config: λ_cost={lambda_cost}, λ_carbon={lambda_carbon}")
    
    loss_fn = DeepOPFNGTLoss(sys_data, config)
    loss_fn.cache_to_gpu(device)
    
    # ============================================================
    # Step 6: Create training DataLoader (with indices for anchor matching)
    # ============================================================
    # CRITICAL FIX: Create DataLoader that returns sample indices
    # This ensures z_anchor_batch matches train_x even with shuffle=True
    class IndexedTensorDataset(Data.Dataset):
        """Dataset that returns (data, index) for proper anchor matching with shuffle."""
        def __init__(self, *tensors):
            assert all(t.size(0) == tensors[0].size(0) for t in tensors)
            self.tensors = tensors
        
        def __getitem__(self, index):
            return tuple(t[index] for t in self.tensors) + (index,)
        
        def __len__(self):
            return self.tensors[0].size(0)
    
    indexed_dataset = IndexedTensorDataset(ngt_data['x_train'], ngt_data['y_train'])
    training_loader = Data.DataLoader(
        dataset=indexed_dataset,
        batch_size=config.ngt_batch_size,
        shuffle=True,  # Now safe to shuffle since we track indices
    )
    print(f"[DeepOPF-NGT Flow] Training DataLoader: {len(training_loader)} batches, "
          f"batch_size={config.ngt_batch_size} (with index tracking)")
    
    # ============================================================
    # Step 7: Setup projection matrix (if enabled)
    # ============================================================
    P_tan_t = None
    if use_projection:
        try:
            from flow_model.post_processing import ConstraintProjectionV2
            print("\n--- Setting up Constraint Projection ---")
            projector = ConstraintProjectionV2(sys_data, config, use_historical_jacobian=True)
            P_tan_full, _, _ = projector.compute_projection_matrix()
            # P_tan_full is (599, 599) for 300-bus: [Vm(300), Va_noslack(299)]
            # Flow output is (465,): [Va_nonZIB_noslack(232), Vm_nonZIB(233)]
            # Need to extract and reorder to match Flow output format
            
            bus_Pnet_all = ngt_data['bus_Pnet_all']  # Non-ZIB buses
            bus_slack = int(sys_data.bus_slack)
            Nbus = config.Nbus
            
            # Build index mapping from Flow output to P_tan_full
            # P_tan_full columns: [Vm(0:300), Va_noslack(300:599)]
            # Flow output: [Va_nonZIB_noslack, Vm_nonZIB]
            
            # Find non-ZIB non-slack buses in original index
            bus_Pnet_noslack = bus_Pnet_all[bus_Pnet_all != bus_slack]
            
            # Indices in P_tan_full format [Vm, Va_noslack]:
            # - Vm part: bus indices directly (0:300)
            # - Va_noslack part: map bus index to Va_noslack position (300+)
            all_buses_noslack = np.concatenate([np.arange(bus_slack), np.arange(bus_slack+1, Nbus)])
            
            # Build mapping: for each bus in bus_Pnet_all/bus_Pnet_noslack, find its column in P_tan_full
            idx_Vm_in_Ptan = bus_Pnet_all  # Vm columns directly use bus index
            idx_Va_in_Ptan = []
            for bus in bus_Pnet_noslack:
                # Find position of bus in all_buses_noslack (Va column index after Vm)
                pos = np.where(all_buses_noslack == bus)[0][0]
                idx_Va_in_Ptan.append(Nbus + pos)
            idx_Va_in_Ptan = np.array(idx_Va_in_Ptan)
            
            # Flow output order: [Va_nonZIB_noslack, Vm_nonZIB]
            # Map to P_tan_full: [idx_Va_in_Ptan, idx_Vm_in_Ptan]
            flow_to_ptan_idx = np.concatenate([idx_Va_in_Ptan, idx_Vm_in_Ptan])
            
            # Extract submatrix for Flow output dimensions
            P_tan_flow = P_tan_full[np.ix_(flow_to_ptan_idx, flow_to_ptan_idx)]
            
            P_tan_t = torch.tensor(P_tan_flow, dtype=torch.float32, device=device)
            print(f"  Full projection matrix shape: {P_tan_full.shape}")
            print(f"  Flow projection matrix shape: {P_tan_t.shape}")
            print(f"  Flow output dim: {len(flow_to_ptan_idx)}")
        except ImportError as e:
            print(f"[Warning] ConstraintProjectionV2 not available ({e}), disabling projection")
            use_projection = False
        except Exception as e:
            print(f"[Warning] Projection setup failed ({e}), disabling projection")
            import traceback
            traceback.print_exc()
            use_projection = False
    
    # ============================================================
    # Step 8: Prepare preference tensor
    # ============================================================
    preference = torch.tensor([[lambda_cost, lambda_carbon]], dtype=torch.float32, device=device)
    
    # ============================================================
    # Step 9: Pre-compute anchors for all training samples
    # ============================================================
    bus_Pnet_all = ngt_data['bus_Pnet_all']
    bus_Pnet_noslack_all = bus_Pnet_all[bus_Pnet_all != bus_slack]
    idx_train = ngt_data['idx_train']
    x_train = ngt_data['x_train'].to(device)  # [Ntrain, 374]
    
    if use_flow_anchor:
        # ==================== Flow Anchor Mode ====================
        # First get VAE anchor, then pass through anchor Flow model
        print("\n--- Pre-computing Flow anchors (Progressive Training) ---")
        print(f"  Step 1: VAE → base anchor (physical space → latent space)")
        
        with torch.no_grad():
            if vae_vm is not None and vae_va is not None:
                # Get VAE predictions (physical space)
                Vm_vae = vae_vm(x_train, use_mean=True)  # [Ntrain, Nbus]
                Va_vae_noslack = vae_va(x_train, use_mean=True)  # [Ntrain, Nbus-1]
                
                # Reconstruct full Va
                Va_vae = torch.zeros(len(idx_train), config.Nbus, device=device)
                Va_vae[:, :bus_slack] = Va_vae_noslack[:, :bus_slack]
                Va_vae[:, bus_slack+1:] = Va_vae_noslack[:, bus_slack:]
                
                # Extract non-ZIB values (physical space)
                Vm_nonZIB = Vm_vae[:, bus_Pnet_all]
                Va_nonZIB_noslack = Va_vae[:, bus_Pnet_noslack_all]
                V_vae_physical = torch.cat([Va_nonZIB_noslack, Vm_nonZIB], dim=1)
                
                # CRITICAL FIX: Convert physical space to pre-sigmoid latent space
                # flow_backward expects latent space input
                eps = 1e-6
                u = (V_vae_physical - Vbias) / (Vscale + 1e-12)  # +1e-12 for numerical safety
                u = torch.clamp(u, eps, 1 - eps)
                z_vae_anchor = torch.log(u / (1 - u))  # logit
            else:
                # Use zeros if VAE not available (zeros in latent space is fine)
                z_vae_anchor = torch.zeros(len(idx_train), output_dim, device=device)
            
            print(f"  VAE base anchor (latent space) shape: {z_vae_anchor.shape}")
            print(f"  z_vae_anchor range: [{z_vae_anchor.min():.4f}, {z_vae_anchor.max():.4f}]")
            
            # Step 2: Pass through anchor Flow model to get better anchor
            print(f"  Step 2: Anchor Flow(pref={anchor_preference}) → training anchor")
            anchor_pref_batch = anchor_pref_tensor.expand(len(idx_train), -1)
            
            # Use the anchor Flow model to generate predictions
            # IMPORTANT: Use detach() to ensure no gradient flows back to anchor model
            z_anchor_all = anchor_flow_model.flow_backward(
                x_train, z_vae_anchor, anchor_pref_batch, 
                num_steps=flow_inf_steps, apply_sigmoid=False, training=False
            ).detach()  # Explicitly detach to prevent gradient flow
        
        print(f"  Flow anchor (latent space) shape: {z_anchor_all.shape}")
        # NOTE: z_anchor_all is in LATENT space (pre-sigmoid), NOT physical Va/Vm!
        # Splitting for debug printing only - these are latent values, not physical
        z_Va_latent = z_anchor_all[:, :ngt_data['NPred_Va']]
        z_Vm_latent = z_anchor_all[:, ngt_data['NPred_Va']:]
        print(f"  z_Va (latent) range: [{z_Va_latent.min():.4f}, {z_Va_latent.max():.4f}]")
        print(f"  z_Vm (latent) range: [{z_Vm_latent.min():.4f}, {z_Vm_latent.max():.4f}]")
        
    else:
        # ==================== VAE Anchor Mode (Default) ====================
        print("\n--- Pre-computing VAE anchors ---")
        print(f"  VAE input shape: {x_train.shape}")
        
        with torch.no_grad():
            # VAE outputs are SCALED/NORMALIZED values, NOT physical values!
            Vm_scaled = vae_vm(x_train, use_mean=True)  # [Ntrain, Nbus] - scaled
            Va_scaled_noslack = vae_va(x_train, use_mean=True)  # [Ntrain, Nbus-1] - scaled
        
        print(f"  VAE Vm output (scaled) shape: {Vm_scaled.shape}")
        print(f"  VAE Va output (scaled) shape: {Va_scaled_noslack.shape}")
        print(f"  VAE Vm scaled range: [{Vm_scaled.min():.4f}, {Vm_scaled.max():.4f}]")
        print(f"  VAE Va scaled range: [{Va_scaled_noslack.min():.4f}, {Va_scaled_noslack.max():.4f}]")
        
        # CRITICAL FIX: Denormalize VAE outputs to physical values!
        # Vm: Vm_physical = Vm_scaled / scale_vm * (VmUb - VmLb) + VmLb
        # Va: Va_physical = Va_scaled / scale_va
        scale_vm = config.scale_vm.item() if hasattr(config.scale_vm, 'item') else float(config.scale_vm)
        scale_va = config.scale_va.item() if hasattr(config.scale_va, 'item') else float(config.scale_va)
        
        VmLb = sys_data.VmLb
        VmUb = sys_data.VmUb
        if isinstance(VmLb, np.ndarray):
            VmLb = torch.from_numpy(VmLb).float().to(device)
            VmUb = torch.from_numpy(VmUb).float().to(device)
        elif isinstance(VmLb, torch.Tensor):
            VmLb = VmLb.to(device)
            VmUb = VmUb.to(device)
        
        # Denormalize Vm
        Vm_anchor_full = Vm_scaled / scale_vm * (VmUb - VmLb) + VmLb
        # Denormalize Va
        Va_anchor_full_noslack = Va_scaled_noslack / scale_va
        
        print(f"  After denormalization:")
        print(f"  Vm physical range: [{Vm_anchor_full.min():.4f}, {Vm_anchor_full.max():.4f}]")
        print(f"  Va physical range: [{Va_anchor_full_noslack.min():.4f}, {Va_anchor_full_noslack.max():.4f}]")
        
        # Reconstruct full Va (add slack=0)
        Va_anchor_full = torch.zeros(len(idx_train), config.Nbus, device=device)
        Va_anchor_full[:, :bus_slack] = Va_anchor_full_noslack[:, :bus_slack]
        Va_anchor_full[:, bus_slack+1:] = Va_anchor_full_noslack[:, bus_slack:]
        
        # Extract non-ZIB values and concatenate as NGT format
        Vm_anchor_nonZIB = Vm_anchor_full[:, bus_Pnet_all]  # [Ntrain, NPred_Vm]
        Va_anchor_nonZIB_noslack = Va_anchor_full[:, bus_Pnet_noslack_all]  # [Ntrain, NPred_Va]
        
        # Concatenate as NGT format: [Va_nonZIB_noslack, Vm_nonZIB] (physical space)
        V_anchor_physical = torch.cat([Va_anchor_nonZIB_noslack, Vm_anchor_nonZIB], dim=1)
        
        print(f"  VAE anchor (physical space) shape: {V_anchor_physical.shape}")
        print(f"  Va anchor range: [{Va_anchor_nonZIB_noslack.min():.4f}, {Va_anchor_nonZIB_noslack.max():.4f}]")
        print(f"  Vm anchor range: [{Vm_anchor_nonZIB.min():.4f}, {Vm_anchor_nonZIB.max():.4f}]")
        
        # CRITICAL FIX: Convert physical space to pre-sigmoid latent space
        # flow_forward_ngt() applies: V_pred = sigmoid(z) * Vscale + Vbias
        # So anchor needs to be in pre-sigmoid space: z = logit((V - Vbias) / Vscale)
        # where logit(p) = log(p / (1-p)) is the inverse of sigmoid
        eps = 1e-6  # Avoid log(0) or log(inf)
        u = (V_anchor_physical - Vbias) / (Vscale + 1e-12)  # +1e-12 for numerical safety
        u = torch.clamp(u, eps, 1 - eps)  # Ensure (0, 1) range
        z_anchor_all = torch.log(u / (1 - u))  # logit function
        
        print(f"  Anchor (pre-sigmoid latent) shape: {z_anchor_all.shape}")
        print(f"  z_anchor range: [{z_anchor_all.min():.4f}, {z_anchor_all.max():.4f}]")
    
    # ============================================================
    # Step 10: Evaluate VAE baseline for TensorBoard reference
    # ============================================================
    vae_baseline_cost = 0.0
    vae_baseline_carbon = 0.0
    if tb_logger:
        print("\n--- Evaluating VAE baseline for TensorBoard reference ---")
        with torch.no_grad():
            # Evaluate VAE anchor on training data
            total_cost = 0.0
            total_carbon = 0.0
            n_samples = 0
            for step, (train_x, train_y, batch_indices) in enumerate(training_loader):
                train_x = train_x.to(device)
                z_anchor_batch = z_anchor_all[batch_indices]
                
                # Convert z_anchor back to physical space (same as flow output)
                V_anchor = torch.sigmoid(z_anchor_batch) * model.Vscale + model.Vbias
                
                _, loss_dict = loss_fn(V_anchor, train_x)
                total_cost += loss_dict.get('loss_cost', 0.0) * len(batch_indices)
                total_carbon += loss_dict.get('loss_carbon', 0.0) * len(batch_indices)
                n_samples += len(batch_indices)
            
            vae_baseline_cost = total_cost / max(n_samples, 1)
            vae_baseline_carbon = total_carbon / max(n_samples, 1)
            vae_baseline_weighted = lambda_cost * vae_baseline_cost + lambda_carbon * vae_baseline_carbon * config.ngt_carbon_scale
            
            print(f"  VAE Baseline - Cost: {vae_baseline_cost:.2f}, Carbon: {vae_baseline_carbon:.4f}")
            print(f"  VAE Baseline - Weighted Objective: {vae_baseline_weighted:.4f}")
    
    # ============================================================
    # Step 11: Training loop
    # ============================================================
    loss_history = {
        'total': [],
        'kgenp_mean': [],
        'kgenq_mean': [],
        'kpd_mean': [],
        'kqd_mean': [],
        'kv_mean': [],
        'cost': [],
        'carbon': [],
    }
    
    n_epochs = config.ngt_Epoch
    batch_size = config.ngt_batch_size
    p_epoch = config.ngt_p_epoch
    s_epoch = config.ngt_s_epoch
    
    print(f"\n{'*' * 5} Training Flow Model {'*' * 5}")
    print(f"Total epochs: {n_epochs}, Print every: {p_epoch} epochs")
    print(f"Estimated batches per epoch: {len(training_loader)}")
    start_time = time.time()
    
    for epoch in range(n_epochs):
        running_loss = 0.0
        running_kgenp = 0.0
        running_kgenq = 0.0
        running_kpd = 0.0
        running_kqd = 0.0
        running_kv = 0.0
        running_cost = 0.0
        running_carbon = 0.0
        n_batches = 0
        
        model.train()
        
        for step, (train_x, train_y, batch_indices) in enumerate(training_loader):
            train_x = train_x.to(device)
            current_batch_size = train_x.shape[0]
            
            # CRITICAL FIX: Use actual batch indices to get matching anchors
            # This correctly handles shuffle=True in DataLoader
            z_anchor_batch = z_anchor_all[batch_indices]
            
            # Expand preference for batch
            pref_batch = preference.expand(current_batch_size, -1)
            
            # PQd batch (same as input for NGT)
            PQd_batch = train_x
            
            # Flow forward: integrate from anchor to get V_pred
            if use_projection and P_tan_t is not None:
                V_pred = flow_forward_ngt_projected(
                    model, train_x, z_anchor_batch, P_tan_t, 
                    pref_batch, flow_inf_steps, training=True
                )
            else:
                V_pred = flow_forward_ngt(
                    model, train_x, z_anchor_batch, 
                    pref_batch, flow_inf_steps, training=True
                )
            
            # Compute loss using existing DeepOPFNGTLoss
            loss, loss_dict = loss_fn(V_pred, PQd_batch)
            
            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            
            # Accumulate losses
            running_loss += loss.item()
            running_kgenp += loss_dict['kgenp_mean']
            running_kgenq += loss_dict['kgenq_mean']
            running_kpd += loss_dict['kpd_mean']
            running_kqd += loss_dict['kqd_mean']
            running_kv += loss_dict['kv_mean']
            running_cost += loss_dict.get('loss_cost', 0.0)
            running_carbon += loss_dict.get('loss_carbon', 0.0)
            n_batches += 1
        
        # NOTE: Removed scheduler.step() to match MLP training exactly
        
        # Average losses for this epoch
        if n_batches > 0:
            avg_loss = running_loss / n_batches
            avg_kgenp = running_kgenp / n_batches
            avg_kgenq = running_kgenq / n_batches
            avg_kpd = running_kpd / n_batches
            avg_kqd = running_kqd / n_batches
            avg_kv = running_kv / n_batches
            avg_cost = running_cost / n_batches
            avg_carbon = running_carbon / n_batches
            
            loss_history['total'].append(avg_loss)
            loss_history['kgenp_mean'].append(avg_kgenp)
            loss_history['kgenq_mean'].append(avg_kgenq)
            loss_history['kpd_mean'].append(avg_kpd)
            loss_history['kqd_mean'].append(avg_kqd)
            loss_history['kv_mean'].append(avg_kv)
            loss_history['cost'].append(avg_cost)
            loss_history['carbon'].append(avg_carbon)
        
        # Print progress
        should_print = (epoch == 0) or ((epoch + 1) % p_epoch == 0)
        if should_print:
            elapsed = time.time() - start_time
            if epoch > 0:
                time_per_epoch = elapsed / (epoch + 1)
                remaining = time_per_epoch * (n_epochs - epoch - 1)
                time_info = f" | Elapsed: {elapsed/60:.1f}min, ETA: {remaining/60:.1f}min"
            else:
                time_info = ""
            
            # Get sample predictions for range info
            # Use same forward function as training (projected vs non-projected)
            with torch.no_grad():
                sample_x = ngt_data['x_train'][:batch_size].to(device)
                sample_anchor = z_anchor_all[:batch_size]
                sample_pref = preference.expand(batch_size, -1)
                if use_projection and P_tan_t is not None:
                    sample_pred = flow_forward_ngt_projected(
                        model, sample_x, sample_anchor, P_tan_t, 
                        sample_pref, flow_inf_steps, training=False
                    )
                else:
                    sample_pred = flow_forward_ngt(model, sample_x, sample_anchor, sample_pref, 
                                                   flow_inf_steps, training=False)
                Va_pred = sample_pred[:, :ngt_data['NPred_Va']]
                Vm_pred = sample_pred[:, ngt_data['NPred_Va']:]
            
            print(f"epoch {epoch+1}/{n_epochs} loss={avg_loss:.4f} "
                  f"Va[{Va_pred.min().item():.4f},{Va_pred.max().item():.4f}] "
                  f"Vm[{Vm_pred.min().item():.4f},{Vm_pred.max().item():.4f}]{time_info}")
            print(f"  [Flow] λ_cost={lambda_cost} λ_carbon={lambda_carbon} steps={flow_inf_steps}")
            print(f"  kgenp={avg_kgenp:.2f} kgenq={avg_kgenq:.2f} "
                  f"kpd={avg_kpd:.2f} kqd={avg_kqd:.2f} kv={avg_kv:.2f}")
        
        # TensorBoard logging (every epoch)
        if tb_logger:
            # Loss components
            tb_logger.log_scalar('loss/total', avg_loss, epoch)
            tb_logger.log_scalar('loss/cost', avg_cost, epoch)
            tb_logger.log_scalar('loss/carbon', avg_carbon, epoch)
            
            # Weighted objective (for comparing optimization progress)
            carbon_scale = getattr(config, 'ngt_carbon_scale', 30.0)
            weighted_obj = lambda_cost * avg_cost + lambda_carbon * avg_carbon * carbon_scale
            tb_logger.log_scalar('objective/weighted', weighted_obj, epoch)
            tb_logger.log_scalar('objective/cost', avg_cost, epoch)
            tb_logger.log_scalar('objective/carbon', avg_carbon, epoch)
            
            # VAE baseline reference (horizontal lines for comparison)
            tb_logger.log_scalar('baseline/vae_cost', vae_baseline_cost, epoch)
            tb_logger.log_scalar('baseline/vae_carbon', vae_baseline_carbon, epoch)
            tb_logger.log_scalar('baseline/vae_weighted', vae_baseline_weighted, epoch)
            
            # Adaptive penalty weights (higher = better constraint satisfaction)
            # Formula: k = min(kcost * L_obj / (L_constraint + eps), k_max)
            # When constraint violation (L_constraint) is small, k is large (capped at k_max)
            tb_logger.log_scalar('weights/kgenp', avg_kgenp, epoch)
            tb_logger.log_scalar('weights/kgenq', avg_kgenq, epoch)
            tb_logger.log_scalar('weights/kpd', avg_kpd, epoch)
            tb_logger.log_scalar('weights/kqd', avg_kqd, epoch)
            tb_logger.log_scalar('weights/kv', avg_kv, epoch)
            
            # Constraint SATISFACTION - WEIGHT NORMALIZATION (indirect indicator)
            # WARNING: k/k_max is NOT the real constraint satisfaction rate!
            # It only indicates that weights are high (constraint violation loss is small on training data)
            tb_logger.log_scalar('satisfaction_weight_norm/Pg', avg_kgenp / 2000.0, epoch)  # kgenp_max=2000
            tb_logger.log_scalar('satisfaction_weight_norm/Qg', avg_kgenq / 2000.0, epoch)  # kgenq_max=2000
            tb_logger.log_scalar('satisfaction_weight_norm/Pd', avg_kpd / 100.0, epoch)     # kpd_max=100
            tb_logger.log_scalar('satisfaction_weight_norm/Qd', avg_kqd / 100.0, epoch)     # kqd_max=100
            tb_logger.log_scalar('satisfaction_weight_norm/V', avg_kv / 500.0, epoch)       # kv_max=500
            
            # Prediction ranges and velocity diagnostics
            with torch.no_grad():
                sample_x = ngt_data['x_train'][:batch_size].to(device)
                sample_anchor = z_anchor_all[:batch_size]
                sample_pref = preference.expand(batch_size, -1)
                
                # Get flow prediction (use same forward function as training)
                if use_projection and P_tan_t is not None:
                    sample_pred_tb = flow_forward_ngt_projected(
                        model, sample_x, sample_anchor, P_tan_t, 
                        sample_pref, flow_inf_steps, training=False
                    )
                else:
                    sample_pred_tb = flow_forward_ngt(model, sample_x, sample_anchor, sample_pref, 
                                                      flow_inf_steps, training=False)
                Va_pred_tb = sample_pred_tb[:, :ngt_data['NPred_Va']]
                Vm_pred_tb = sample_pred_tb[:, ngt_data['NPred_Va']:]
                
                # Convert anchor back to physical space for comparison
                sample_anchor_physical = torch.sigmoid(sample_anchor) * model.Vscale + model.Vbias
                Va_anchor = sample_anchor_physical[:, :ngt_data['NPred_Va']]
                Vm_anchor = sample_anchor_physical[:, ngt_data['NPred_Va']:]
                
                # Velocity diagnostics: how much did Flow change from anchor?
                delta_Va = (sample_pred_tb[:, :ngt_data['NPred_Va']] - Va_anchor).abs()
                delta_Vm = (sample_pred_tb[:, ngt_data['NPred_Va']:] - Vm_anchor).abs()
                
                # Direct velocity at t=0 (what the model outputs at anchor)
                t_zero = torch.zeros(sample_x.shape[0], 1, device=device)
                velocity_at_anchor = model.predict_velocity(sample_x, sample_anchor, t_zero, sample_pref)
                velocity_norm = velocity_at_anchor.norm(dim=1).mean()
                
                # Compute REAL constraint satisfaction rate
                # (numpy already imported at top of file)
                
                # Reconstruct full voltage from Flow prediction
                xam_P = np.insert(sample_pred_tb.cpu().numpy(), ngt_data['idx_bus_Pnet_slack'][0], 0, axis=1)
                Va_len_with_slack = ngt_data['NPred_Va'] + 1
                Va_nonZIB = xam_P[:, :Va_len_with_slack]
                Vm_nonZIB = xam_P[:, Va_len_with_slack:Va_len_with_slack + ngt_data['NPred_Vm']]
                Vx = Vm_nonZIB * np.exp(1j * Va_nonZIB)
                
                # Recover ZIB voltages if needed
                if ngt_data['NZIB'] > 0 and ngt_data.get('param_ZIMV') is not None:
                    Vy = np.dot(ngt_data['param_ZIMV'], Vx.T).T
                else:
                    Vy = None
                
                Ve = np.zeros((batch_size, config.Nbus))
                Vf = np.zeros((batch_size, config.Nbus))
                Ve[:, ngt_data['bus_Pnet_all']] = Vx.real
                Vf[:, ngt_data['bus_Pnet_all']] = Vx.imag
                if Vy is not None:
                    Ve[:, ngt_data['bus_ZIB_all']] = Vy.real
                    Vf[:, ngt_data['bus_ZIB_all']] = Vy.imag
                
                Pred_Vm_sample = np.sqrt(Ve**2 + Vf**2)
                Pred_Va_sample = np.arctan2(Vf, Ve)
                Pred_V_sample = Pred_Vm_sample * np.exp(1j * Pred_Va_sample)
                
                # Get sample load data
                sample_x_np = sample_x.cpu().numpy()
                num_Pd = len(ngt_data['bus_Pd'])
                Pd_sample = np.zeros((batch_size, config.Nbus))
                Qd_sample = np.zeros((batch_size, config.Nbus))
                Pd_sample[:, ngt_data['bus_Pd']] = sample_x_np[:, :num_Pd]
                Qd_sample[:, ngt_data['bus_Qd']] = sample_x_np[:, num_Pd:]
                
                # Compute power flow
                Pred_Pg_sample, Pred_Qg_sample, _, _ = get_genload(
                    Pred_V_sample, Pd_sample, Qd_sample,
                    sys_data.bus_Pg, sys_data.bus_Qg, sys_data.Ybus
                )
                
                # Calculate real constraint satisfaction
                MAXMIN_Pg = ngt_data['MAXMIN_Pg']
                MAXMIN_Qg = ngt_data['MAXMIN_Qg']
                _, _, _, _, _, vio_PQg_sample, _, _, _, _ = get_vioPQg(
                    Pred_Pg_sample, sys_data.bus_Pg, MAXMIN_Pg,
                    Pred_Qg_sample, sys_data.bus_Qg, MAXMIN_Qg,
                    config.DELTA
                )
                if torch.is_tensor(vio_PQg_sample):
                    vio_PQg_sample = vio_PQg_sample.numpy()
                
                real_Pg_satisfy = np.mean(vio_PQg_sample[:, 0])
                real_Qg_satisfy = np.mean(vio_PQg_sample[:, 1])
                
                # Voltage satisfaction
                VmLb = config.ngt_VmLb
                VmUb = config.ngt_VmUb
                Vm_vio_upper = np.mean(Pred_Vm_sample > VmUb) * 100
                Vm_vio_lower = np.mean(Pred_Vm_sample < VmLb) * 100
                real_Vm_satisfy = 100 - Vm_vio_upper - Vm_vio_lower
                
                # Log REAL satisfaction rates
                tb_logger.log_scalar('satisfaction_real/Pg', real_Pg_satisfy, epoch)
                tb_logger.log_scalar('satisfaction_real/Qg', real_Qg_satisfy, epoch)
                tb_logger.log_scalar('satisfaction_real/Vm', real_Vm_satisfy, epoch)
            
            # Prediction ranges
            tb_logger.log_scalar('pred/Va_min', Va_pred_tb.min().item(), epoch)
            tb_logger.log_scalar('pred/Va_max', Va_pred_tb.max().item(), epoch)
            tb_logger.log_scalar('pred/Vm_min', Vm_pred_tb.min().item(), epoch)
            tb_logger.log_scalar('pred/Vm_max', Vm_pred_tb.max().item(), epoch)
            
            # Velocity/movement diagnostics
            tb_logger.log_scalar('velocity/norm_at_t0', velocity_norm.item(), epoch)
            tb_logger.log_scalar('velocity/delta_Va_mean', delta_Va.mean().item(), epoch)
            tb_logger.log_scalar('velocity/delta_Vm_mean', delta_Vm.mean().item(), epoch)
            tb_logger.log_scalar('velocity/delta_Va_max', delta_Va.max().item(), epoch)
            tb_logger.log_scalar('velocity/delta_Vm_max', delta_Vm.max().item(), epoch)
            
            # Anchor (VAE) baseline ranges for reference
            tb_logger.log_scalar('anchor/Va_min', Va_anchor.min().item(), epoch)
            tb_logger.log_scalar('anchor/Va_max', Va_anchor.max().item(), epoch)
            tb_logger.log_scalar('anchor/Vm_min', Vm_anchor.min().item(), epoch)
            tb_logger.log_scalar('anchor/Vm_max', Vm_anchor.max().item(), epoch)
        
        # Save models periodically
        if (epoch + 1) % 100 == 0 and (epoch + 1) >= s_epoch:
            lc_str = f"{lambda_cost:.1f}".replace('.', '')
            save_path = f'{config.model_save_dir}/NetV_ngt_flow_{config.Nbus}bus_lc{lc_str}_E{epoch+1}.pth'
            torch.save(model.state_dict(), save_path, _use_new_zipfile_serialization=False)
            print(f"  Model saved: {save_path}")
    
    time_train = time.time() - start_time
    print(f"\nTraining completed in {time_train:.2f} seconds ({time_train/60:.2f} minutes)")
    
    # Save final model
    lc_str = f"{lambda_cost:.1f}".replace('.', '')
    final_path = f'{config.model_save_dir}/NetV_ngt_flow_{config.Nbus}bus_lc{lc_str}_E{n_epochs}_final.pth'
    torch.save(model.state_dict(), final_path, _use_new_zipfile_serialization=False)
    print(f"Final model saved: {final_path}")
    
    # Return projection info for evaluation
    return model, loss_history, time_train, ngt_data, sys_data, use_projection, P_tan_t

# --- from: /home/yuepeng/code/multi_objective_opf/main_part/train.py (L705-L1054) ---
def train_unsupervised_ngt(config, lambda_cost, lambda_carbon, sys_data=None, device=None, tb_logger=None):
    """
    DeepOPF-NGT Unsupervised Training - EXACTLY matching reference implementation.
    
    This function uses a SINGLE NetV model to predict [Va, Vm] for non-ZIB nodes,
    exactly as in main_DeepOPFNGT_M3.ipynb. It does NOT use the dual-model architecture
    (NetVm + NetVa) that supervised training uses.
    
    Key differences from supervised training:
    1. Single NetV model (not separate Vm/Va models)
    2. Output includes sigmoid with scale/bias for physical constraints
    3. Uses Kron Reduction: only predicts non-ZIB nodes
    4. Unsupervised loss with analytical Jacobian backward
    5. Adaptive penalty weight scheduling
    
    Loss function:
    L = k_cost * L_cost + k_genp * L_Pg + k_genq * L_Qg + k_pd * L_Pd + k_qd * L_Qd + k_v * L_V
    
    Args:
        config: Configuration object with ngt_* parameters
        sys_data: PowerSystemData object (optional, will load if None)
        device: Device (optional, uses config.device if None)
        tb_logger: TensorBoardLogger instance for logging (optional)
        
    Returns:
        model: Trained NetV model
        loss_history: Dictionary of training losses
        time_train: Training time in seconds
        ngt_data: NGT training data dictionary
        sys_data: Updated system data
    """ 
    
    print('=' * 60)
    print('DeepOPF-NGT Unsupervised Training (Reference Implementation)')
    print('=' * 60)
    
    # Device setup
    if device is None:
        device = config.device
    
    # ============================================================
    # Step 1: Load NGT-specific training data
    # ============================================================
    ngt_data, sys_data = load_ngt_training_data(config, sys_data)
    
    input_dim = ngt_data['input_dim']
    output_dim = ngt_data['output_dim']
    Vscale = ngt_data['Vscale'].to(device)
    Vbias = ngt_data['Vbias'].to(device)
    
    print(f"\nModel configuration:")
    print(f"  Input dim: {input_dim}")
    print(f"  Output dim: {output_dim} (Va: {ngt_data['NPred_Va']}, Vm: {ngt_data['NPred_Vm']})")
    print(f"  Hidden layers: {config.ngt_khidden}")
    print(f"  Epochs: {config.ngt_Epoch}")
    print(f"  Batch size: {config.ngt_batch_size}")
    print(f"  Learning rate: {config.ngt_Lr}")
    
    # ============================================================
    # Step 2: Create NetV model (single unified model)
    # ============================================================
    model = NetV(
        input_channels=input_dim,
        output_channels=output_dim,
        hidden_units=config.ngt_hidden_units,
        khidden=config.ngt_khidden,
        Vscale=Vscale,
        Vbias=Vbias
    )
    model.to(device)
    
    print(f"\nNetV model created:")
    print(f"  Total parameters: {sum(p.numel() for p in model.parameters()):,}")
    
    # ============================================================
    # Step 3: Create optimizer (Adam with NGT learning rate)
    # ============================================================
    optimizer = torch.optim.Adam(model.parameters(), lr=config.ngt_Lr)
    
    # ============================================================
    # Step 4: Create loss function (Penalty_V with custom backward)
    # ============================================================
    config.ngt_lambda_cost = lambda_cost
    config.ngt_lambda_carbon = lambda_carbon
    loss_fn = DeepOPFNGTLoss(sys_data, config)
    
    # Pre-cache parameters to GPU for faster training
    loss_fn.cache_to_gpu(device)
    
    # ============================================================
    # Step 5: Create training DataLoader
    # ============================================================
    training_loader = create_ngt_training_loader(ngt_data, config)
    
    # Prepare PQd tensor for all training samples
    PQd_tensor = ngt_data['PQd_train'].to(device)
    
    # ============================================================
    # Step 6: Training loop (exactly matching reference)
    # ============================================================
    loss_history = {
        'total': [],
        'kgenp_mean': [],
        'kgenq_mean': [],
        'kpd_mean': [],
        'kqd_mean': [],
        'kv_mean': [],
        # Multi-objective components (always present for compatibility)
        'cost': [],
        'carbon': [],
    }
    
    # Check if multi-objective mode is enabled
    use_multi_objective = getattr(config, 'ngt_use_multi_objective', False)
    
    n_epochs = config.ngt_Epoch
    batch_size = config.ngt_batch_size
    p_epoch = config.ngt_p_epoch
    s_epoch = config.ngt_s_epoch
    
    print(f"\n{'*' * 5} Training {'*' * 5}")
    print(f"Total epochs: {n_epochs}, Print every: {p_epoch} epochs")
    print(f"Estimated batches per epoch: {len(training_loader)}")
    start_time = time.time()  # Use wall-clock time (not process_time which ignores GPU)
    
    for epoch in range(n_epochs):
        running_loss = 0.0
        running_kgenp = 0.0
        running_kgenq = 0.0
        running_kpd = 0.0
        running_kqd = 0.0
        running_kv = 0.0
        running_cost = 0.0
        running_carbon = 0.0
        n_batches = 0
        
        model.train()
        
        for step, (train_x, train_y) in enumerate(training_loader):
            train_x = train_x.to(device)
            current_batch_size = train_x.shape[0] 
            
            # train_x is the input: [Pd_nonzero, Qd_nonzero] / baseMVA
            # This IS the PQd data, just need to pass it correctly
            PQd_batch = train_x  # Input IS the load data in p.u.
            
            # Forward pass - model outputs [Va_nonZIB_noslack, Vm_nonZIB] with sigmoid
            yvtrain_hat = model(train_x)
            
            # Compute loss (Penalty_V.apply)
            loss, loss_dict = loss_fn(yvtrain_hat, PQd_batch)
            
            # Backward pass (uses custom analytical Jacobian)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            # Accumulate losses
            running_loss += loss.item()
            running_kgenp += loss_dict['kgenp_mean']
            running_kgenq += loss_dict['kgenq_mean']
            running_kpd += loss_dict['kpd_mean']
            running_kqd += loss_dict['kqd_mean']
            running_kv += loss_dict['kv_mean']
            running_cost += loss_dict.get('loss_cost', 0.0)
            running_carbon += loss_dict.get('loss_carbon', 0.0)
            n_batches += 1
        
        # Average losses for this epoch
        if n_batches > 0:
            avg_loss = running_loss / n_batches
            avg_kgenp = running_kgenp / n_batches
            avg_kgenq = running_kgenq / n_batches
            avg_kpd = running_kpd / n_batches
            avg_kqd = running_kqd / n_batches
            avg_kv = running_kv / n_batches
            avg_cost = running_cost / n_batches
            avg_carbon = running_carbon / n_batches
            
            loss_history['total'].append(avg_loss)
            loss_history['kgenp_mean'].append(avg_kgenp)
            loss_history['kgenq_mean'].append(avg_kgenq)
            loss_history['kpd_mean'].append(avg_kpd)
            loss_history['kqd_mean'].append(avg_kqd)
            loss_history['kv_mean'].append(avg_kv)
            loss_history['cost'].append(avg_cost)
            loss_history['carbon'].append(avg_carbon)
        
        # Print progress (matching reference format)
        # Print first epoch immediately, then every p_epoch epochs
        should_print = (epoch == 0) or ((epoch + 1) % p_epoch == 0)
        if should_print:
            # Estimate time remaining using wall-clock time
            elapsed = time.time() - start_time
            if epoch > 0:
                time_per_epoch = elapsed / (epoch + 1)
                remaining = time_per_epoch * (n_epochs - epoch - 1)
                time_info = f" | Elapsed: {elapsed/60:.1f}min, ETA: {remaining/60:.1f}min"
            else:
                time_info = ""
            
            # Get sample predictions for range info
            with torch.no_grad():
                sample_pred = model(ngt_data['x_train'][:batch_size].to(device))
                Va_pred = sample_pred[:, :ngt_data['NPred_Va']]
                Vm_pred = sample_pred[:, ngt_data['NPred_Va']:]
            
            print(f"epoch {epoch+1}/{n_epochs} loss={avg_loss:.4f} "
                  f"Va[{Va_pred.min().item():.4f},{Va_pred.max().item():.4f}] "
                  f"Vm[{Vm_pred.min().item():.4f},{Vm_pred.max().item():.4f}]{time_info}")
            print(f"  kcost={config.ngt_kcost} kgenp={avg_kgenp:.2f} kgenq={avg_kgenq:.2f} "
                  f"kpd={avg_kpd:.2f} kqd={avg_kqd:.2f} kv={avg_kv:.2f}")
            # Print multi-objective info if enabled
            if use_multi_objective:
                lambda_cost = getattr(config, 'ngt_lambda_cost', 0.9)
                lambda_carbon = getattr(config, 'ngt_lambda_carbon', 0.1)
                print(f"  [Multi-Obj] cost={avg_cost:.2f} carbon={avg_carbon:.4f} "
                      f"λ_cost={lambda_cost} λ_carbon={lambda_carbon}")
        
        # TensorBoard logging (every epoch, not just print epochs)
        if tb_logger:
            # Loss components
            tb_logger.log_scalar('loss/total', avg_loss, epoch)
            tb_logger.log_scalar('loss/cost', avg_cost, epoch)
            tb_logger.log_scalar('loss/carbon', avg_carbon, epoch)
            
            # Weighted objective (for comparing optimization progress)
            lambda_cost_val = getattr(config, 'ngt_lambda_cost', 0.9)
            lambda_carbon_val = getattr(config, 'ngt_lambda_carbon', 0.1)
            carbon_scale = getattr(config, 'ngt_carbon_scale', 30.0)
            weighted_obj = lambda_cost_val * avg_cost + lambda_carbon_val * avg_carbon * carbon_scale
            tb_logger.log_scalar('objective/weighted', weighted_obj, epoch)
            tb_logger.log_scalar('objective/cost', avg_cost, epoch)
            tb_logger.log_scalar('objective/carbon', avg_carbon, epoch)
            
            # Adaptive penalty weights (higher = better constraint satisfaction)
            # Formula: k = min(kcost * L_obj / (L_constraint + eps), k_max)
            # When constraint violation (L_constraint) is small, k is large (capped at k_max)
            tb_logger.log_scalar('weights/kgenp', avg_kgenp, epoch)
            tb_logger.log_scalar('weights/kgenq', avg_kgenq, epoch)
            tb_logger.log_scalar('weights/kpd', avg_kpd, epoch)
            tb_logger.log_scalar('weights/kqd', avg_kqd, epoch)
            tb_logger.log_scalar('weights/kv', avg_kv, epoch)
            
            # Constraint SATISFACTION - WEIGHT NORMALIZATION (indirect indicator)
            # WARNING: k/k_max is NOT the real constraint satisfaction rate!
            # It only indicates that weights are high (constraint violation loss is small on training data)
            tb_logger.log_scalar('satisfaction_weight_norm/Pg', avg_kgenp / 2000.0, epoch)  # kgenp_max=2000
            tb_logger.log_scalar('satisfaction_weight_norm/Qg', avg_kgenq / 2000.0, epoch)  # kgenq_max=2000
            tb_logger.log_scalar('satisfaction_weight_norm/Pd', avg_kpd / 100.0, epoch)     # kpd_max=100
            tb_logger.log_scalar('satisfaction_weight_norm/Qd', avg_kqd / 100.0, epoch)     # kqd_max=100
            tb_logger.log_scalar('satisfaction_weight_norm/V', avg_kv / 500.0, epoch)       # kv_max=500
            
            # REAL Constraint Satisfaction Rate (actual violation check)
            # Compute on a sample batch to get true satisfaction rates
            with torch.no_grad():
                sample_pred = model(ngt_data['x_train'][:batch_size].to(device))
                Va_pred_tb = sample_pred[:, :ngt_data['NPred_Va']]
                Vm_pred_tb = sample_pred[:, ngt_data['NPred_Va']:]
                
                # Compute real constraint satisfaction using get_vioPQg
                # Reconstruct full voltage and compute power flow
                # (numpy already imported at top of file)
                
                # Reconstruct full voltage from NGT format
                xam_P = np.insert(sample_pred.cpu().numpy(), ngt_data['idx_bus_Pnet_slack'][0], 0, axis=1)
                Va_len_with_slack = ngt_data['NPred_Va'] + 1
                Va_nonZIB = xam_P[:, :Va_len_with_slack]
                Vm_nonZIB = xam_P[:, Va_len_with_slack:Va_len_with_slack + ngt_data['NPred_Vm']]
                Vx = Vm_nonZIB * np.exp(1j * Va_nonZIB)
                
                # Recover ZIB voltages if needed
                if ngt_data['NZIB'] > 0 and ngt_data.get('param_ZIMV') is not None:
                    Vy = np.dot(ngt_data['param_ZIMV'], Vx.T).T
                else:
                    Vy = None
                
                Ve = np.zeros((batch_size, config.Nbus))
                Vf = np.zeros((batch_size, config.Nbus))
                Ve[:, ngt_data['bus_Pnet_all']] = Vx.real
                Vf[:, ngt_data['bus_Pnet_all']] = Vx.imag
                if Vy is not None:
                    Ve[:, ngt_data['bus_ZIB_all']] = Vy.real
                    Vf[:, ngt_data['bus_ZIB_all']] = Vy.imag
                
                Pred_Vm_sample = np.sqrt(Ve**2 + Vf**2)
                Pred_Va_sample = np.arctan2(Vf, Ve)
                Pred_V_sample = Pred_Vm_sample * np.exp(1j * Pred_Va_sample)
                
                # Get sample load data
                sample_x_np = ngt_data['x_train'][:batch_size].cpu().numpy()
                num_Pd = len(ngt_data['bus_Pd'])
                Pd_sample = np.zeros((batch_size, config.Nbus))
                Qd_sample = np.zeros((batch_size, config.Nbus))
                Pd_sample[:, ngt_data['bus_Pd']] = sample_x_np[:, :num_Pd]
                Qd_sample[:, ngt_data['bus_Qd']] = sample_x_np[:, num_Pd:]
                
                # Compute power flow
                Pred_Pg_sample, Pred_Qg_sample, _, _ = get_genload(
                    Pred_V_sample, Pd_sample, Qd_sample,
                    sys_data.bus_Pg, sys_data.bus_Qg, sys_data.Ybus
                )
                
                # Calculate real constraint satisfaction
                MAXMIN_Pg = ngt_data['MAXMIN_Pg']
                MAXMIN_Qg = ngt_data['MAXMIN_Qg']
                _, _, _, _, _, vio_PQg_sample, _, _, _, _ = get_vioPQg(
                    Pred_Pg_sample, sys_data.bus_Pg, MAXMIN_Pg,
                    Pred_Qg_sample, sys_data.bus_Qg, MAXMIN_Qg,
                    config.DELTA
                )
                if torch.is_tensor(vio_PQg_sample):
                    vio_PQg_sample = vio_PQg_sample.numpy()
                
                real_Pg_satisfy = np.mean(vio_PQg_sample[:, 0])
                real_Qg_satisfy = np.mean(vio_PQg_sample[:, 1])
                
                # Voltage satisfaction
                VmLb = config.ngt_VmLb
                VmUb = config.ngt_VmUb
                Vm_vio_upper = np.mean(Pred_Vm_sample > VmUb) * 100
                Vm_vio_lower = np.mean(Pred_Vm_sample < VmLb) * 100
                real_Vm_satisfy = 100 - Vm_vio_upper - Vm_vio_lower
                
                # Log REAL satisfaction rates
                tb_logger.log_scalar('satisfaction_real/Pg', real_Pg_satisfy, epoch)
                tb_logger.log_scalar('satisfaction_real/Qg', real_Qg_satisfy, epoch)
                tb_logger.log_scalar('satisfaction_real/Vm', real_Vm_satisfy, epoch)
            tb_logger.log_scalar('pred/Va_min', Va_pred_tb.min().item(), epoch)
            tb_logger.log_scalar('pred/Va_max', Va_pred_tb.max().item(), epoch)
            tb_logger.log_scalar('pred/Vm_min', Vm_pred_tb.min().item(), epoch)
            tb_logger.log_scalar('pred/Vm_max', Vm_pred_tb.max().item(), epoch)
        
        # Save models periodically (include lambda_cost in filename for multi-preference training)
        if (epoch + 1) % 100 == 0 and (epoch + 1) >= s_epoch:
            lc_str = f"_lc{config.ngt_lambda_cost:.1f}" if use_multi_objective else ""
            save_path = f'{config.model_save_dir}/NetV_ngt_{config.Nbus}bus{lc_str}_E{epoch+1}.pth'
            torch.save(model.state_dict(), save_path, _use_new_zipfile_serialization=False)
            print(f"  Model saved: {save_path}")
    
    time_train = time.time() - start_time
    print(f"\nTraining completed in {time_train:.2f} seconds ({time_train/60:.2f} minutes)")
    
    # Save final model (include lambda_cost in filename for multi-preference training)
    lc_str = f"_lc{config.ngt_lambda_cost:.1f}" if use_multi_objective else "_single"
    final_path = f'{config.model_save_dir}/NetV_ngt_{config.Nbus}bus{lc_str}_E{n_epochs}_final.pth'
    torch.save(model.state_dict(), final_path, _use_new_zipfile_serialization=False)
    print(f"Final model saved: {final_path}")
    
    return model, loss_history, time_train, ngt_data, sys_data

